[package]
name = "animboom-ffi"
version.workspace = true
edition.workspace = true
authors.workspace = true

[build-dependencies]
cbindgen = "0.24.0"

[dev-dependencies]
assert2 = "0.3.11"

[dependencies]
libc = "0.2.144"
animboom-toolkit = { path = "../animboom-toolkit" }
